# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
